import {Lexend} from "next/font/google";
import "./globals.css";

const lexend = Lexend({ weight: "500", subsets: ["latin"] });

export const metadata = {
  title: "Attendance App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${lexend.className}`}>
        {children}
      </body>
    </html>
  );
}
